fun main() {

    val k = 100
    val board = Board(k)

    //Glider (szybowiec)
//    board.fieldList[1][2].isAlive = true
//    board.fieldList[2][3].isAlive = true
//    board.fieldList[3][1].isAlive = true
//    board.fieldList[3][2].isAlive = true
//    board.fieldList[3][3].isAlive = true

    //Blinker (swiatla uliczne)
//    board.fieldList[1][2].isAlive = true
//    board.fieldList[2][2].isAlive = true
//    board.fieldList[3][2].isAlive = true

    //zabka
//    board.fieldList[2][1].isAlive = true
//    board.fieldList[2][2].isAlive = true
//    board.fieldList[3][3].isAlive = true
//    board.fieldList[4][0].isAlive = true
//    board.fieldList[5][1].isAlive = true
//    board.fieldList[5][2].isAlive = true

//    //dakota > glider > klocek
    board.fieldList[24][1].isAlive = true
    board.fieldList[24][2].isAlive = true
    board.fieldList[24][3].isAlive = true
    board.fieldList[24][4].isAlive = true
    board.fieldList[25][4].isAlive = true
    board.fieldList[26][4].isAlive = true
    board.fieldList[27][3].isAlive = true
    board.fieldList[25][0].isAlive = true
    board.fieldList[27][0].isAlive = true
    board.fieldList[42][62].isAlive = true
    board.fieldList[43][62].isAlive = true
    board.fieldList[43][63].isAlive = true
    board.fieldList[43][64].isAlive = true
    board.fieldList[43][65].isAlive = true
    board.fieldList[44][46].isAlive = true
    board.fieldList[44][63].isAlive = true
    board.fieldList[44][64].isAlive = true
    board.fieldList[44][65].isAlive = true
    board.fieldList[44][66].isAlive = true
    board.fieldList[44][72].isAlive = true
    board.fieldList[44][73].isAlive = true
    board.fieldList[45][45].isAlive = true
    board.fieldList[45][47].isAlive = true
    board.fieldList[45][53].isAlive = true
    board.fieldList[45][54].isAlive = true
    board.fieldList[45][63].isAlive = true
    board.fieldList[45][66].isAlive = true
    board.fieldList[45][72].isAlive = true
    board.fieldList[45][73].isAlive = true
    board.fieldList[46][38].isAlive = true
    board.fieldList[46][39].isAlive = true
    board.fieldList[46][43].isAlive = true
    board.fieldList[46][44].isAlive = true
    board.fieldList[46][48].isAlive = true
    board.fieldList[46][63].isAlive = true
    board.fieldList[46][64].isAlive = true
    board.fieldList[46][65].isAlive = true
    board.fieldList[46][66].isAlive = true
    board.fieldList[47][38].isAlive = true
    board.fieldList[47][39].isAlive = true
    board.fieldList[47][43].isAlive = true
    board.fieldList[47][44].isAlive = true
    board.fieldList[47][48].isAlive = true
    board.fieldList[47][53].isAlive = true
    board.fieldList[47][55].isAlive = true
    board.fieldList[47][57].isAlive = true
    board.fieldList[47][58].isAlive = true
    board.fieldList[47][62].isAlive = true
    board.fieldList[47][63].isAlive = true
    board.fieldList[47][64].isAlive = true
    board.fieldList[47][65].isAlive = true
    board.fieldList[48][43].isAlive = true
    board.fieldList[48][44].isAlive = true
    board.fieldList[48][48].isAlive = true
    board.fieldList[48][54].isAlive = true
    board.fieldList[48][55].isAlive = true
    board.fieldList[48][59].isAlive = true
    board.fieldList[48][62].isAlive = true
    board.fieldList[49][45].isAlive = true
    board.fieldList[49][47].isAlive = true
    board.fieldList[49][58].isAlive = true
    board.fieldList[50][46].isAlive = true
    board.fieldList[50][55].isAlive = true
    board.fieldList[50][58].isAlive = true
    board.fieldList[54][65].isAlive = true
    board.fieldList[55][66].isAlive = true
    board.fieldList[56][64].isAlive = true
    board.fieldList[56][65].isAlive = true
    board.fieldList[56][66].isAlive = true
    board.fieldList[70][13].isAlive = true
    board.fieldList[70][14].isAlive = true
    board.fieldList[70][20].isAlive = true
    board.fieldList[70][21].isAlive = true
    board.fieldList[71][14].isAlive = true
    board.fieldList[71][15].isAlive = true
    board.fieldList[71][19].isAlive = true
    board.fieldList[71][20].isAlive = true
    board.fieldList[72][11].isAlive = true
    board.fieldList[72][14].isAlive = true
    board.fieldList[72][16].isAlive = true
    board.fieldList[72][18].isAlive = true
    board.fieldList[72][20].isAlive = true
    board.fieldList[72][23].isAlive = true
    board.fieldList[73][11].isAlive = true
    board.fieldList[73][12].isAlive = true
    board.fieldList[73][13].isAlive = true
    board.fieldList[73][15].isAlive = true
    board.fieldList[73][16].isAlive = true
    board.fieldList[73][18].isAlive = true
    board.fieldList[73][19].isAlive = true
    board.fieldList[73][21].isAlive = true
    board.fieldList[73][22].isAlive = true
    board.fieldList[73][23].isAlive = true
    board.fieldList[74][12].isAlive = true
    board.fieldList[74][14].isAlive = true
    board.fieldList[74][16].isAlive = true
    board.fieldList[74][18].isAlive = true
    board.fieldList[74][20].isAlive = true
    board.fieldList[74][22].isAlive = true
    board.fieldList[75][13].isAlive = true
    board.fieldList[75][14].isAlive = true
    board.fieldList[75][15].isAlive = true
    board.fieldList[75][19].isAlive = true
    board.fieldList[75][20].isAlive = true
    board.fieldList[75][21].isAlive = true
    board.fieldList[77][13].isAlive = true
    board.fieldList[77][14].isAlive = true
    board.fieldList[77][15].isAlive = true
    board.fieldList[77][19].isAlive = true
    board.fieldList[77][20].isAlive = true
    board.fieldList[77][21].isAlive = true
    board.fieldList[78][12].isAlive = true
    board.fieldList[78][14].isAlive = true
    board.fieldList[78][16].isAlive = true
    board.fieldList[78][18].isAlive = true
    board.fieldList[78][20].isAlive = true
    board.fieldList[78][22].isAlive = true
    board.fieldList[79][11].isAlive = true
    board.fieldList[79][12].isAlive = true
    board.fieldList[79][13].isAlive = true
    board.fieldList[79][15].isAlive = true
    board.fieldList[79][16].isAlive = true
    board.fieldList[79][18].isAlive = true
    board.fieldList[79][19].isAlive = true
    board.fieldList[79][21].isAlive = true
    board.fieldList[79][22].isAlive = true
    board.fieldList[79][23].isAlive = true
    board.fieldList[80][11].isAlive = true
    board.fieldList[80][14].isAlive = true
    board.fieldList[80][16].isAlive = true
    board.fieldList[80][18].isAlive = true
    board.fieldList[80][20].isAlive = true
    board.fieldList[80][23].isAlive = true
    board.fieldList[81][14].isAlive = true
    board.fieldList[81][15].isAlive = true
    board.fieldList[81][19].isAlive = true
    board.fieldList[81][20].isAlive = true
    board.fieldList[82][13].isAlive = true
    board.fieldList[82][14].isAlive = true
    board.fieldList[82][20].isAlive = true
    board.fieldList[82][21].isAlive = true

    GameOfLife(board)


}